api_groups:
    path:     /
    defaults: { _controller: "MiwPadelBundle:Groups:index" }
    methods: [GET]
    
api_groups_create:
    path:     /
    defaults: { _controller: "MiwPadelBundle:Groups:create" }
    methods:  [POST]

api_groups_show:
    path:     /{id}.{format}
    defaults: { _controller: "MiwPadelBundle:Groups:show", format: json }
    methods: [GET]

api_groups_update:
    path:     /{id}
    defaults: { _controller: "MiwPadelBundle:Groups:update" }
    methods:  [PUT]

api_groups_delete:
    path:     /{id}
    defaults: { _controller: "MiwPadelBundle:Groups:delete" }
    methods:  [DELETE]
    
api_groups_add_user:
    path:     /{id}/users/{userId}
    defaults: { _controller: "MiwPadelBundle:Groups:addUser" }
    methods:  [POST]
