api_users:
    path:     /
    defaults: { _controller: "MiwPadelBundle:Users:index" }

api_users_show:
    path:     /{id}/show
    defaults: { _controller: "MiwPadelBundle:Users:show" }

api_users_new:
    path:     /new
    defaults: { _controller: "MiwPadelBundle:Users:new" }

api_users_create:
    path:     /create
    defaults: { _controller: "MiwPadelBundle:Users:create" }
    methods:  POST

api_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "MiwPadelBundle:Users:edit" }

api_users_update:
    path:     /{id}/update
    defaults: { _controller: "MiwPadelBundle:Users:update" }
    methods:  [POST, PUT]

api_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "MiwPadelBundle:Users:delete" }
    methods:  [POST, DELETE]
