api_users:
    path:     /
    defaults: { _controller: "MiwPadelBundle:Users:index" }
    methods: [GET]
    
api_users_create:
    path:     /
    defaults: { _controller: "MiwPadelBundle:Users:create" }
    methods:  [POST]

api_users_show:
    path:     /{id}.{format}
    defaults: { _controller: "MiwPadelBundle:Users:show", format: json }
    methods: [GET]

api_users_update:
    path:     /{id}
    defaults: { _controller: "MiwPadelBundle:Users:update" }
    methods:  [PUT]

api_users_delete:
    path:     /{id}
    defaults: { _controller: "MiwPadelBundle:Users:delete" }
    methods:  [DELETE]
    
api_groups_add_to_group:
    path:     /{id}/groups/{groupId}
    defaults: { _controller: "MiwPadelBundle:Users:addToGroup" }
    methods:  [POST]
